site_name: Aeromat.io

theme:
  name: material
  logo: assets/logo.svg
  custom_dir: overrides/
  palette:
    scheme: slate
    primary: black
    accent: blue

  font:
    text: Roboto
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.expand
  extensions:
    - material.extensions.emoji

plugins:
  - search
  - privacy
  - tags
  - blog

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/columns.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Home: index.md
  - Services:
      - Overview: services/index.md
      - Contract Manufacturing: services/contract-manufacturing.md
      - CNC Machining: services/cnc-machining.md
      - Plastic Fabrication: services/plastic-fabrication.md
  - Industries:
      - Overview: industries/index.md
      - Semiconductor: industries/semiconductor.md
      - Laboratory: industries/laboratory.md
      - Food and Beverage: industries/food-beverage.md
      - Medical: industries/medical.md
  - Blog: blog/index.md
  - Contact: contact.md